#!/bin/bash

echo "🚀 Hugo Tranquilpeak 4000 - Repository Setup"
echo "=============================================="
echo ""
echo "This is a modernized fork of the Hugo Tranquilpeak theme."
echo "The repository is already set up and ready to use!"
echo ""
echo "To contribute back to the original theme:"
echo ""
echo "1. Go to https://github.com/kakawait/hugo-tranquilpeak-theme"
echo "2. Click 'Fork' to create your own fork"
echo "3. Copy your fork URL (it will look like: https://github.com/YOUR_USERNAME/hugo-tranquilpeak-theme)"
echo ""
echo "Then run these commands:"
echo ""
echo "# Add your fork as origin (replace YOUR_USERNAME with your GitHub username)"
echo "git remote add origin https://github.com/YOUR_USERNAME/hugo-tranquilpeak-theme.git"
echo ""
echo "# Push to your fork"
echo "git push -u origin master"
echo ""
echo "# Create a pull request by going to:"
echo "https://github.com/kakawait/hugo-tranquilpeak-theme/compare"
echo ""
echo "Or use GitHub CLI:"
echo "gh pr create --repo kakawait/hugo-tranquilpeak-theme --title 'Modernize theme for Hugo v0.148+' --body-file pr-body.md"
echo ""
echo "The theme is ready to be used! 🎉" 