name: Setup Node.js and Dependencies

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '20'
        type: string
      install-deps:
        description: 'Whether to install dependencies'
        required: false
        default: true
        type: boolean
      build-assets:
        description: 'Whether to build assets'
        required: false
        default: false
        type: boolean

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        if: inputs.install-deps
        run: npm ci

      - name: Build theme assets
        if: inputs.build-assets
        run: npm run build 
