name: Test Latest Hugo Versions

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  test-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - 'latest'  # Latest stable release
          - 'latest-dev'  # Latest development version

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: ./.github/actions/setup-hugo
      with:
        hugo-version: ${{ matrix.hugo-version }}
        extended: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build theme assets
      run: npm run build

    - name: Setup theme
      uses: ./.github/actions/setup-theme

    - name: Test with example site
      uses: ./.github/actions/hugo-build

    - name: Check for build errors
      run: |
        cd exampleSite
        if [ -d "public" ]; then
          echo "✅ Build successful with Hugo ${{ matrix.hugo-version }}"
          echo "Generated files:"
          find public -type f | head -20
        else
          echo "❌ Build failed with Hugo ${{ matrix.hugo-version }}"
          exit 1
        fi

    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Theme compatibility issue with Hugo ${{ matrix.hugo-version }}`,
            body: `The theme failed to build with Hugo ${{ matrix.hugo-version }}.
          
          **Workflow:** ${context.workflow}
          **Run ID:** ${context.runId}
          **Commit:** ${context.sha}
          
          Please investigate and fix compatibility issues.`,
            labels: ['bug', 'hugo-compatibility']
          });
          console.log(`Created issue: ${issue.data.html_url}`); 
