name: Validate GitHub Actions

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install actionlint
      uses: reviewdog/action-actionlint@v1.65.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        fail_on_error: true
        filter_mode: diff_context 
